@file:JvmName("RegistryGenerator")

package com.binge.designsystem.catalogregistry

import java.io.File
import kotlin.system.exitProcess

private const val CATALOG_PACKAGE = "com.binge.designsystem.catalog"
private const val REGISTRY_PACKAGE = "com.binge.designsystem.catalogapp.registry"

/** Raised when a catalog file holds a public `…Sample` the registry cannot list. */
class UnregistrableSampleException(
    val problems: List<String>,
) : IllegalStateException("Cannot register catalog samples:\n" + problems.joinToString("\n") { "  $it" })

/**
 * Renders `CatalogRegistry.kt` from the catalog's source files, given as `(file name, text)` pairs.
 * Sorted by group then name so the output is stable whatever order the files arrive in.
 */
fun generateRegistry(files: List<Pair<String, String>>): String {
    val results = files.map { (name, text) -> SampleScanner.scan(name, text) }
    val problems = results.flatMap { it.problems }
    if (problems.isNotEmpty()) throw UnregistrableSampleException(problems)
    val samples = results.flatMap { it.samples }.sortedWith(compareBy({ it.group }, { it.name }, { it.function }))
    return buildString {
        appendLine("// Generated by :catalog-registry from designsystem/…/catalog. Do not edit.")
        appendLine("package $REGISTRY_PACKAGE")
        appendLine()
        samples.forEach { appendLine("import $CATALOG_PACKAGE.${it.function}") }
        appendLine()
        appendLine("val CatalogRegistry: List<CatalogEntry> =")
        appendLine("    listOf(")
        samples.forEach { sample ->
            appendLine("        CatalogEntry(")
            appendLine("            id = ${sample.function.literal()},")
            appendLine("            group = ${sample.group.literal()},")
            appendLine("            name = ${sample.name.literal()},")
            appendLine("            description = ${sample.description.literal()},")
            appendLine("            content = { ${sample.function}() },")
            appendLine("        ),")
        }
        appendLine("    )")
    }
}

private fun String.literal(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$") + "\""

/** `args`: the catalog source directory, then the file to write. */
fun main(args: Array<String>) {
    require(args.size == 2) { "usage: <catalog source dir> <output file>" }
    val sources = File(args[0]).listFiles { file -> file.extension == "kt" }.orEmpty().sortedBy { it.name }
    try {
        val registry = generateRegistry(sources.map { it.name to it.readText() })
        File(args[1]).apply { parentFile.mkdirs() }.writeText(registry)
    } catch (e: UnregistrableSampleException) {
        System.err.println(e.message)
        exitProcess(1)
    }
}
