@file:JvmName("RegistryGenerator")

package com.binge.designsystem.catalogregistry

import java.io.File
import kotlin.system.exitProcess

private const val PHONE_CATALOG_PACKAGE = "com.binge.designsystem.catalog"
private const val REGISTRY_PACKAGE = "com.binge.designsystem.catalogapp.registry"

/** Raised when a catalog file holds a public `…Sample` the registry cannot list. */
class UnregistrableSampleException(
    val problems: List<String>,
) : IllegalStateException("Cannot register catalog samples:\n" + problems.joinToString("\n") { "  $it" })

/**
 * Renders a registry file from a catalog's source files, given as `(file name, text)` pairs, with
 * the samples in [catalogPackage] listed in a top-level `val` named [registryName]. Sorted by group
 * then name so the output is stable whatever order the files arrive in.
 */
fun generateRegistry(
    files: List<Pair<String, String>>,
    catalogPackage: String = PHONE_CATALOG_PACKAGE,
    registryName: String = "CatalogRegistry",
): String {
    val results = files.map { (name, text) -> SampleScanner.scan(name, text) }
    val problems = results.flatMap { it.problems }
    if (problems.isNotEmpty()) throw UnregistrableSampleException(problems)
    val samples = results.flatMap { it.samples }.sortedWith(compareBy({ it.group }, { it.name }, { it.function }))
    return buildString {
        appendLine("// Generated by :catalog-registry from the design system's catalog sources. Do not edit.")
        appendLine("package $REGISTRY_PACKAGE")
        appendLine()
        samples.forEach { appendLine("import $catalogPackage.${it.function}") }
        appendLine()
        appendLine("val $registryName: List<CatalogEntry> =")
        appendLine("    listOf(")
        samples.forEach { sample ->
            appendLine("        CatalogEntry(")
            appendLine("            id = ${sample.function.literal()},")
            appendLine("            group = ${sample.group.literal()},")
            appendLine("            name = ${sample.name.literal()},")
            appendLine("            description = ${sample.description.literal()},")
            appendLine("            kind = CatalogKind.${sample.kind.name},")
            appendLine("            content = { ${sample.function}() },")
            appendLine("        ),")
        }
        appendLine("    )")
    }
}

private fun String.literal(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$") + "\""

/**
 * `args`: the output directory, then one `<registry name>=<catalog package>=<source dir>` per registry.
 * Each is written to `<registry name>.kt`, so the phone and TV activities list only their own samples.
 */
fun main(args: Array<String>) {
    require(args.size >= 2) { "usage: <output dir> <registry name>=<catalog package>=<source dir>..." }
    val outputDir = File(args[0]).apply { mkdirs() }
    val problems = mutableListOf<String>()
    args.drop(1).forEach { spec ->
        val (registryName, catalogPackage, sourceDir) = spec.split("=", limit = 3)
        val sources = File(sourceDir).listFiles { file -> file.extension == "kt" }.orEmpty().sortedBy { it.name }
        try {
            val registry = generateRegistry(sources.map { it.name to it.readText() }, catalogPackage, registryName)
            File(outputDir, "$registryName.kt").writeText(registry)
        } catch (e: UnregistrableSampleException) {
            problems += e.problems
        }
    }
    if (problems.isNotEmpty()) {
        System.err.println(UnregistrableSampleException(problems).message)
        exitProcess(1)
    }
}
