@file:JvmName("RegistryGenerator")

package com.binge.designsystem.catalogregistry

import java.io.File
import kotlin.system.exitProcess

private const val PHONE_CATALOG_PACKAGE = "com.binge.designsystem.catalog"
private const val REGISTRY_PACKAGE = "com.binge.designsystem.catalogapp.registry"

/** Raised when a catalog file holds a public `…Sample` the registry cannot list. */
class UnregistrableSampleException(
    val problems: List<String>,
) : IllegalStateException("Cannot register catalog samples:\n" + problems.joinToString("\n") { "  $it" })

/**
 * Renders a registry file from a catalog's source files, given as `(file name, text)` pairs, with
 * the samples in [catalogPackage] listed in a top-level `val` named [registryName]. Entries are
 * gathered into components ([toComponents]); files are read in name order so the output is stable
 * whatever order they arrive in.
 */
fun generateRegistry(
    files: List<Pair<String, String>>,
    catalogPackage: String = PHONE_CATALOG_PACKAGE,
    registryName: String = "CatalogRegistry",
): String {
    val results = files.sortedBy { it.first }.map { (name, text) -> SampleScanner.scan(name, text) }
    val problems = results.flatMap { it.problems }
    if (problems.isNotEmpty()) throw UnregistrableSampleException(problems)
    val entries = toComponents(results.flatMap { it.samples })
    return buildString {
        appendLine("// Generated by :catalog-registry from the design system's catalog sources. Do not edit.")
        appendLine("package $REGISTRY_PACKAGE")
        appendLine()
        entries.map { it.declaration.function }.sorted().forEach { appendLine("import $catalogPackage.$it") }
        appendLine()
        appendLine("val $registryName: List<CatalogEntry> =")
        appendLine("    listOf(")
        entries.forEach { entry ->
            val sample = entry.declaration
            appendLine("        CatalogEntry(")
            appendLine("            id = ${sample.function.literal()},")
            appendLine("            group = ${entry.component.literal()},")
            appendLine("            groupName = ${entry.componentName.literal()},")
            appendLine("            name = ${entry.variantName.literal()},")
            appendLine("            description = ${sample.description.literal()},")
            appendLine("            kind = CatalogKind.${sample.kind.name},")
            appendLine("            onePerScreen = ${sample.onePerScreen},")
            appendLine("            fullScreen = ${sample.fullScreen},")
            appendLine("            selfDescribing = ${sample.selfDescribing},")
            appendLine("            content = { ${sample.function}() },")
            appendLine("        ),")
        }
        appendLine("    )")
    }
}

private fun String.literal(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$") + "\""

/**
 * `args`: the output directory, then one `<registry name>=<catalog package>=<source dir>` per registry.
 * Each is written to `<registry name>.kt`, so the phone and TV activities list only their own samples.
 */
fun main(args: Array<String>) {
    require(args.size >= 2) { "usage: <output dir> <registry name>=<catalog package>=<source dir>..." }
    val outputDir = File(args[0]).apply { mkdirs() }
    val problems = mutableListOf<String>()
    args.drop(1).forEach { spec ->
        val (registryName, catalogPackage, sourceDir) = spec.split("=", limit = 3)
        val sources = File(sourceDir).listFiles { file -> file.extension == "kt" }.orEmpty().sortedBy { it.name }
        try {
            val registry = generateRegistry(sources.map { it.name to it.readText() }, catalogPackage, registryName)
            File(outputDir, "$registryName.kt").writeText(registry)
        } catch (e: UnregistrableSampleException) {
            problems += e.problems
        }
    }
    if (problems.isNotEmpty()) {
        System.err.println(UnregistrableSampleException(problems).message)
        exitProcess(1)
    }
}
